install:
	pip install -e .[dev]

test:
	pytest -q

coverage:
	pytest --cov=multimodal_agent --cov-report=term-missing

format:
	black .
	isort .

lint:
	flake8 src

build:
	python -m build

publish-test:
	twine upload --repository testpypi dist/*

publish:
	twine upload dist/*
